### ISSUE TITLE
Nagiosgraph not working

### ISSUE THREAD

**Issue by herbalizer404** [JasonRivers/Docker-Nagios#67] opened 2018-05-23 15:02 UTC
I created my different dirs, chown 999 to nagios dirs. 
I launched the same command as yours, but when I try to see a graph, i ve this error in my logs:
`Can't locate ngshared.pm in @INC (you may need to install the ngshared module) (@INC contains: /opt/nagiosgraph/etc /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /opt/nagiosgraph/bin/insert.pl line 41.
BEGIN failed--compilation aborted at /opt/nagiosgraph/bin/insert.pl line 41.`

**Comment by herbalizer404** [comment] 2018-05-23 15:12
Or maybe, what are the good rights to apply to the directories?

**Comment by nicocolt** [comment] 2018-07-03 17:01
Hello,

Same issue here:

`Can't locate ngshared.pm in @INC (you may need to install the ngshared module) (@INC contains: /opt/nagiosgraph/etc /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /opt/nagiosgraph/bin/insert.pl line 41`

I've tried with latest, 4.4.0 and 4.3.2. Maybe I have missed something ?

Let me know,
Best
Nicolas

**Comment by vhristev** [comment] 2018-07-04 09:39
Yeaa there is some issue with perl path like /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 ...etc. 

The workaround is to reinstall NagiosGraph. Here is how you can do that:

Start your container with volumes
#Enter your container
docker exec -it nagios4 /bin/bash 

#Clean /opt/nagiosgraph folder --- you will receive ...etc and ... var are busy dont worry.
rm -rf /opt/nagiosgraph

#Build your NagiosGraph --- you dont need to download it its already there just reinstall it. 
cd /tmp/nagiosgraph                                                          && \
    ./install.pl --install                                      \
        --prefix /opt/nagiosgraph                               \
        --nagios-user ${NAGIOS_USER}                            \
        --www-user ${NAGIOS_USER}                               \
        --nagios-perfdata-file ${NAGIOS_HOME}/var/perfdata.log  \
        --nagios-cgi-url /cgi-bin                               \
                                                                     && \
    cp share/nagiosgraph.ssi ${NAGIOS_HOME}/share/ssi/common-header.ssi

No errors anymore.

**Comment by JasonRivers** [comment] 2018-07-04 09:44
I'd like to get more info on this, I am not seeing these errors at all.
Which log are you seeing these errors in?
Are you running the latest 4.4.1?
Are you getting the error when it's creating graphs or when you're trying to view them within Nagios?
What is the "action_url" you are using?

**Comment by vhristev** [comment] 2018-07-04 09:51
Which log are you seeing these errors in? --- Docker logs ... docker logs -f nagios4
Are you running the latest 4.4.1? --- yes its latest build 4.4.1
Are you getting the error when it's creating graphs or when you're trying to view them within Nagios? --- when you run the container you get the errors in the logs so graphs are not working at all.
What is the "action_url" you are using? --- I dont think is relevant the problem is when /opt/nagiosgraph/bin/insert.pl script is executed its searching python in /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 the problem is the /usr/share/lib folder does not contain anything. 

That issues is only when you specify volumes for nagiosgraph (options below). If you dont use them its fine. If you run it without volumes if fine. As I said I didn't deep dive what is the problem I just reinstall it and now its fine. 
-v /path-to-nagiosgraph-var:/opt/nagiosgraph/var \
  -v /path-to-nagiosgraph-etc:/opt/nagiosgraph/etc \

#Docker log pastebin
https://www.pastiebin.com/5b3c978f2fe63

**Comment by JasonRivers** [comment] 2018-07-04 09:55
Thanks, OK so this looks like the nagiosgraph install is putting files in either etc, so when externally mounted those files are no longer in-place. I understand the issue, I'll take a look and see if I can get the install of nagiosgraph to be a little more sensible with where it's putting files it requires.

**Comment by vhristev** [comment] 2018-07-04 09:58
You can mount share over any folder and the filesystem will use latest mount. If you unmount the volume you will start seeing files from first mount ,so solution is to: 
mount volume before installation
copy files somewhere mount and then move them back

**Comment by JasonRivers** [comment] 2018-07-04 10:40
Yep, That is one option to copy files after the container starts (I do this with example configs if there is no configs found), The alternative will be to have those files elsewhere anyway, I am looking at both options right now.

**Comment by JasonRivers** [comment] 2018-07-04 12:02
@vhristev once dockerhub has built the latest commit, this should fix this issue, If the required file is not in /opt/nagiosgraph/etc then it will re-run the installation, in my tests, it is renaming the existing config files with a date if they exist. This will only run if ngshared.pm is not in the directory.

**Comment by JasonRivers** [comment] 2018-07-04 12:03
@herbalizer404  @nicocolt ^^

**Comment by nicocolt** [comment] 2018-07-05 13:45
Hello,

Got this issue with the new image:
`Warning: File '/opt/nagios/var/perfdata.log' could not be opened - service performance data will not be written to file!
nagios: Warning: File '/opt/nagios/var/perfdata.log' could not be opened - service performance data will not be written to file!
Error: Unable to create temp file '/opt/nagios/var/nagios.tmpwmeo2C' for writing status data: Permission denied
nagios: Error: Unable to create temp file '/opt/nagios/var/nagios.tmpwmeo2C' for writing status data: Permission denied`

Reinstall of nagiosgraph shows this error: `nagios not found in any of:`

my running command is, as root:
`docker container run -d --name nagios4 -v /root/docker-nagios/etc:/opt/nagios/etc -v /root/docker-nagios/var:/opt/nagios/var -v /root/docker-nagios/Custom-Nagios-Plugins:/opt/Custom-Nagios-Plugins -v /root/docker-nagios/nagiosgraph/var:/opt/nagiosgraph/var -v /root/docker-nagios/nagiosgraph/etc:/opt/nagiosgraph/etc -p 0.0.0.0:8080:80 jasonrivers/nagios:latest`

Best regards

**Comment by vhristev** [comment] 2018-07-05 13:48
That is permissions related. 

When you create your volume folders you must be sure your docker user can write in those folders. So if you create it with 'root' account change owner to your docker user. I dont know with which user your docker is running so check it out with "ps aux | grep docker" 

If you want more info about that check that post: https://denibertovic.com/posts/handling-permissions-with-docker-volumes/

**Comment by nicocolt** [comment] 2018-07-05 14:11
Thanks for your quick reply,

Docker is running as root too. Directories created by docker run belongs to
root too. Volumes are created when running docker run command.

Best regards



2018-07-05 15:48 GMT+02:00 Valentin Hristev <notifications@github.com>:

**Comment by vhristev** [comment] 2018-07-05 14:17
Im not sure what you exactly doing but you can see its permissions issue in the log. 
 Unable to create temp file '/opt/nagios/var/nagios.tmpwmeo2C' for writing status data: Permission denied 

Volumes are share points if you don't create the folders below and give them correct permissions its not going to work. Folders below must exist with correct permission. When you start docker with -v its not creating the folders for you: 
Try commands below:
### Create folders
mkdir /root/docker-nagios/etc /root/docker-nagios/var /root/docker-nagios/Custom-Nagios-Plugins /root/docker-nagios/nagiosgraph/var /root/docker-nagios/nagiosgraph/etc

### Just for the test give 777 permissions. 
chmod -R 777 /root/docker-nagios/etc /root/docker-nagios/var /root/docker-nagios/Custom-Nagios-Plugins /root/docker-nagios/nagiosgraph/var /root/docker-nagios/nagiosgraph/etc

**Comment by JasonRivers** [comment] 2018-07-05 14:33
@nicocolt latest commit should take ownership of the directories when Nagios starts.

**Comment by nicocolt** [comment] 2018-07-05 15:30
Hello,

With the latest image, and chmod 777, it works. Without chmod it does not
work. I don't think so chmod to 777 is a good idea though.

Any ideas?

Best regards



2018-07-05 16:33 GMT+02:00 Jason Rivers <notifications@github.com>:

**Comment by vhristev** [comment] 2018-07-05 15:32
JasonRivers last post is that he fix permissions ,so pull the latest code  and try again.

As I said its a matter of user ownership ,so when you run the image you can see which user ID is creating files and chown to that ID

**Comment by nicocolt** [comment] 2018-07-05 15:36
I have pulled the latest image from 41 minutes ago. Where I can find the
UID, by ls -l on the docker-nagios directory i think ?

Best regards

2018-07-05 17:32 GMT+02:00 Valentin Hristev <notifications@github.com>:

**Comment by nicocolt** [comment] 2018-07-06 17:14
Hello,

It works. With chmod 777. I will check later with 755. For now, nagios is
running through docker on a dedicated server that I want to monitor. In
other words, I want to monitor the host where the docker nagios server is
running. I'm facing an issue with SSL handshake between nrpe service
installed on the host and the docker nagios server.

Is it a possible configuration? Or have I to install docker nagios server
on another host?

Thanks for your answer,
Best regards,
Nico


2018-07-05 17:36 GMT+02:00 Nicolas Loison <nicolas.loison1@gmail.com>:

**Comment by JasonRivers** [comment] 2018-07-09 08:09
@nicocolt This should work fine, I do exactly that, What version of NRPE are you running on the host? I recommend using version 3.2.1 (Which is what the nagios container is running), Is it failing for other hosts or only the host that the container is running on? Could you raise a new issue for this and include your config for monitoring the host?

**Comment by nicocolt** [comment] 2018-07-11 14:54
Hello,

I managed to get it works on my local environment.
I have added the docker bridge network in the allowed hosts in nrpe
configuration. By the way, I used a v2 nrpe, which cause some errors. I
have to installed v 3.2.1.

Thanks,
Nico

--

2018-07-09 10:09 GMT+02:00 Jason Rivers <notifications@github.com>:

**Comment by nicocolt** [comment] 2018-07-12 08:23
Hello,

I can not find a way to install nrpre v3 other than by sources. On a
production server, I'm not pretty confident to install compilation
binaries. Is there a way to find a package binary for nrpe v3 on Ubuntu
server ?

Let me know,
Thanks.
Nico

--


2018-07-11 16:54 GMT+02:00 Nicolas Loison <nicolas.loison1@gmail.com>:

**Comment by JasonRivers** [comment] 2018-07-12 10:13
I'm not sure about a binary package for NRPE I have always compiled from source because distro packages are always out of date. Please raise a new issue if you want further help.

**Comment by JasonRivers** [comment] 2018-07-12 10:14
Closing as I believe original issue is resolved.

**Closed by JasonRivers** 2018-07-12 10:14 UTC

**Comment by samz-github** [comment] 2019-03-21 09:55
This issue is not resolved yet..

**Comment by itsmepetrov** [comment] 2019-03-21 10:39
same here

**Comment by mabazyar** [comment] 2019-04-04 18:50
> Yeaa there is some issue with perl path like /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 ...etc.
> 
> The workaround is to reinstall NagiosGraph. Here is how you can do that:
> 
> Start your container with volumes
> #Enter your container
> docker exec -it nagios4 /bin/bash
> 
> #Clean /opt/nagiosgraph folder --- you will receive ...etc and ... var are busy dont worry.
> rm -rf /opt/nagiosgraph
> 
> #Build your NagiosGraph --- you dont need to download it its already there just reinstall it.
> cd /tmp/nagiosgraph && 
> ./install.pl --install 
> --prefix /opt/nagiosgraph 
> --nagios-user ${NAGIOS_USER} 
> --www-user ${NAGIOS_USER} 
> --nagios-perfdata-file ${NAGIOS_HOME}/var/perfdata.log 
> --nagios-cgi-url /cgi-bin 
> && 
> cp share/nagiosgraph.ssi ${NAGIOS_HOME}/share/ssi/common-header.ssi
> 
> No errors anymore.

It works like a dream for me...Thanks for sharing your experience 👍

**Comment by davorceman** [comment] 2019-05-10 07:35
Hello, just to say...  I'm also getting this error with 4.4.3 version
  Can't locate ngshared.pm in @INC (you may need to install the ngshared module) (@INC contains: /opt/nagiosgraph/etc /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /opt/nagiosgraph/bin/insert.pl line 41.

**Comment by kaka987** [comment] 2019-05-30 09:20
https://github.com/mconf/nagios-etc/blob/master/nagiosgraph/ngshared.pm
It works ok after putting the file here: nagiosgraph/etc

**Comment by ibotheperfect** [comment] 2020-03-17 12:04
I had same issue. Then I realized because of I mount my own empty nagiosgraph/etc directory nagios can not see any conf and ngshared.pm file. I fixed issue by creating another container without any volume mount and copy all files from /opt/nagiosgraph/etc to old one. To fix these issue nagios_start may create all these files when etc directory is empty.

**Comment by jonnymccullagh** [comment] 2023-01-18 14:52
I fell over this issue today and would recommend that the documentation/readme be updated. Recommending the volume mount for nagiosgraph-etc was added in [PR 64](https://github.com/JasonRivers/Docker-Nagios/pull/64/files) but I have opened [PR 146](https://github.com/JasonRivers/Docker-Nagios/pull/146) to remove that line from the readme.
`/opt/nagiosgraph/etc` contains the following files by default. 
```
access.conf     labels.conf               nagiosgraph-nagios.cfg  nagiosgraph_fr.conf
datasetdb.conf  map                       nagiosgraph.conf        ngshared.pm
groupdb.conf    nagiosgraph-apache.conf   nagiosgraph_de.conf     rrdopts.conf
hostdb.conf     nagiosgraph-commands.cfg  nagiosgraph_es.conf     servdb.conf
```
Mounting an empty volume at that location hides these files. I would suggest that new users do not want that to happen and experienced users will be able to copy those files out before mounting a volume over it.

**Comment by i15e** [comment] 2024-01-11 17:03
Per the comments above I worked around this by creating a temporary container and copying `/opt/nagiosgraph/etc` to the host filesystem's `nagiosgraph` basedir:

```shell
(c=$(docker create jasonrivers/nagios:latest) && {
   sudo docker cp -a $c:/opt/nagiosgraph/etc /HOST/PATH/TO/nagiosgraph
   docker rm $c >/dev/null
})
```
